# Daily Data Science 001

This one is for the Numpy Library from start.

# Numpy

## Creation

In [ ]:
# creation of numpy arrays

# first we have to import the numpy library, if not present install it using pip install numpy
import numpy as np

# using this shorthand we can create numpy arrays

In [6]:
# simple creation of 1D (vector) array
a = np.array([1, 2, 3, 4, 5])
print(type(a))
a

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [7]:
# we can also create 2D (matrix) or 3D (tensor) arrays using nested lists
b = np.array([[1, 2, 3], [4, 5, 6]])
print(type(b))
print(b)

c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(type(c))
print(c)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
# We can also use list or tuple comprehensions to create arrays
d = np.array([i for i in range(1, 11)])
print(d)

e = np.array([(i, i**2) for i in range(1, 6)])
print(e)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]
 [ 5 25]]


In [33]:
# now let's try to pass a python dict set to the array function
my_dict = {'a': 1, 'b': 2, 'c': 3}
f = np.array(my_dict)
print(f)
type(f)

my_set = {1, 2, 2, 3, 4, 5, 5}
g = np.array(my_set)
print(g)
type(g)

{'a': 1, 'b': 2, 'c': 3}
{1, 2, 3, 4, 5}


numpy.ndarray

## Functions

In [28]:
# we can also change the data type of the array elements using dtype parameter
d = np.array([1, 2, 3, 4, 5], dtype=float)
print(d)
print(d.dtype)

e = np.array([1, 0, 3, -1, 5], dtype=bool)
print(e)
print(e.dtype)

[1. 2. 3. 4. 5.]
float64
[ True False  True  True  True]
bool


In [13]:
# arrange function to create arrays with a range of values
f = np.arange(0, 10)  # start, stop
print(f)


# if you want to use the step parameter with floating point numbers, you can use the linspace function instead
g = np.linspace(0, 1, 5)  # start, stop, steps
print(g)

[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]


In [14]:
# reshape function to change the shape of an array
h = np.arange(1, 13)
print(h)
h_reshaped = h.reshape(3,4) # reshape to 3 rows and 4 columns
print(h_reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
# these functions can be used simultaneously too
np.arange(1, 13).reshape(3, 4)[0][0].dtype

dtype('int64')

In [34]:
print(np.ones((2, 3))) # create a 2x3 array of ones
print()
print(np.zeros((4, 5))) # create a 4x5 array of zeros
print()
print(np.eye(3)) # create a 3x3 identity matrix

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
# Now we will use the random module of numpy to create random arrays
print(np.random.rand(3, 4)) # create a 3x4 array of random numbers between 0 and 1
print()
print(np.random.randint(0, 10, (2, 5))) # create a 2x5 array of random integers between 0 and 10

[[0.55213232 0.85834848 0.01932931 0.62989043]
 [0.99226958 0.90064566 0.87553985 0.84651962]
 [0.44879729 0.84441032 0.29271073 0.70343627]]

[[3 0 6 0 8]
 [6 6 3 8 5]]


In [38]:
# To control the randomness we can set the seed value
np.random.seed(42)
print(np.random.rand(3, 4)) # create a 3x4 array of random numbers between 0 and 1
print()
print(np.random.randint(0, 10, (2, 5))) # create a 2x5 array of random integers between 0 and 10

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]

[[5 1 4 0 9]
 [5 8 0 9 2]]


In [ ]:
# linespace and arange functions can also be used to create arrays with specific ranges and steps
print(np.arange(0, 10, 2)) # create an array of even numbers
print()
print(np.linspace(0, 1, 5)) # create an array of 5

# linespace linearlly generates values between the start and stop values, while arange generates values with a specific step size. So if you want to create an array of 5 values between 0 and 1, you can use linspace, but if you want to create an array of even numbers between 0 and 10, you can use arange with a step size of 2.
# while arrange is more flexible and can be used to create arrays with specific step sizes, linspace is more precise and can be used to create arrays with a specific number of values between a range.

[0 2 4 6 8]

[0.   0.25 0.5  0.75 1.  ]
