# Daily Data Science 001

This one is for the Numpy Library from start, learning about creation, splitting, slicing, indexing, functions, attribute etc.

# Numpy

## Creation

In [1]:
# creation of numpy arrays

# first we have to import the numpy library, if not present install it using pip install numpy
import numpy as np

# using this shorthand we can create numpy arrays

In [2]:
# simple creation of 1D (vector) array
a = np.array([1, 2, 3, 4, 5])
print(type(a))
a

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [3]:
# we can also create 2D (matrix) or 3D (tensor) arrays using nested lists
b = np.array([[1, 2, 3], [4, 5, 6]])
print(type(b))
print(b)

c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(type(c))
print(c)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# We can also use list or tuple comprehensions to create arrays
d = np.array([i for i in range(1, 11)])
print(d)

e = np.array([(i, i**2) for i in range(1, 6)])
print(e)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]
 [ 5 25]]


In [5]:
# now let's try to pass a python dict set to the array function
my_dict = {'a': 1, 'b': 2, 'c': 3}
f = np.array(my_dict)
print(f)
type(f)

my_set = {1, 2, 2, 3, 4, 5, 5}
g = np.array(my_set)
print(g)
type(g)

{'a': 1, 'b': 2, 'c': 3}
{1, 2, 3, 4, 5}


numpy.ndarray

## Functions

In [6]:
# we can also change the data type of the array elements using dtype parameter
d = np.array([1, 2, 3, 4, 5], dtype=float)
print(d)
print(d.dtype)

e = np.array([1, 0, 3, -1, 5], dtype=bool)
print(e)
print(e.dtype)

[1. 2. 3. 4. 5.]
float64
[ True False  True  True  True]
bool


In [7]:
# arrange function to create arrays with a range of values
f = np.arange(0, 10)  # start, stop
print(f)


# if you want to use the step parameter with floating point numbers, you can use the linspace function instead
g = np.linspace(0, 1, 5)  # start, stop, steps
print(g)

[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]


In [8]:
# reshape function to change the shape of an array
h = np.arange(1, 13)
print(h)
h_reshaped = h.reshape(3,4) # reshape to 3 rows and 4 columns
print(h_reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
# these functions can be used simultaneously too
np.arange(1, 13).reshape(3, 4)[0][0].dtype

dtype('int64')

In [10]:
print(np.ones((2, 3))) # create a 2x3 array of ones
print()
print(np.zeros((4, 5))) # create a 4x5 array of zeros
print()
print(np.eye(3)) # create a 3x3 identity matrix

[[1. 1. 1.]
 [1. 1. 1.]]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# Now we will use the random module of numpy to create random arrays
print(np.random.rand(3, 4)) # create a 3x4 array of random numbers between 0 and 1
print()
print(np.random.randint(0, 10, (2, 5))) # create a 2x5 array of random integers between 0 and 10

[[0.09916273 0.70882582 0.04210891 0.01898041]
 [0.87750004 0.85850093 0.51335883 0.64553643]
 [0.05311705 0.62557606 0.44928838 0.93010409]]

[[1 7 0 5 4]
 [6 2 0 4 1]]


In [12]:
# To control the randomness we can set the seed value
np.random.seed(42)
print(np.random.rand(3, 4)) # create a 3x4 array of random numbers between 0 and 1
print()
print(np.random.randint(0, 10, (2, 5))) # create a 2x5 array of random integers between 0 and 10

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]

[[5 1 4 0 9]
 [5 8 0 9 2]]


In [13]:
# linespace and arange functions can also be used to create arrays with specific ranges and steps
print(np.arange(0, 10, 2)) # create an array of even numbers
print()
print(np.linspace(0, 1, 5)) # create an array of 5

# linespace linearlly generates values between the start and stop values, while arange generates values with a specific step size. So if you want to create an array of 5 values between 0 and 1, you can use linspace, but if you want to create an array of even numbers between 0 and 10, you can use arange with a step size of 2.
# while arrange is more flexible and can be used to create arrays with specific step sizes, linspace is more precise and can be used to create arrays with a specific number of values between a range.

[0 2 4 6 8]

[0.   0.25 0.5  0.75 1.  ]


In [14]:
# Simple way to create identity matrix
print(np.eye(4)) # create a 4x4 identity matrix
print(np.identity(4)) # create a 4x4 identity matrix


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Attributes

In [15]:
# To find the dimensions of an array we can use the ndim attribute
print(a.ndim) # number of dimensions

# Now to find the shape of an array we can use the shape attribute
print(a.shape) # shape of the array ->> (2, 3) (where 2 means 2 rows and 3 means 3 columns)


b = np.array([[[1,2], [3, 4]], [[5, 6], [7, 8]]], dtype=np.int16)
print(b.ndim) # number of dimensions now it is 3 because it has 3 levels of nesting (blocks, rows, columns)
print(b.shape) # shape of the array ->> (2, 2, 2) (where 2 means 2 blocks, 2 means 2 rows and 2 means 2 columns)

1
(5,)
3
(2, 2, 2)


In [16]:
# Now to find the size of an array we can use the size attribute
print(a.size) # size of the array ->> 6 (total number of elements in
print(b.size) # size of the array ->> 8 (total number of elements in the array)

# This tells me the total number of elements in the array, now to find the size of the element we can use the item-size attribute
print(a.itemsize)
print(b.itemsize)

5
8
8
2


In [17]:
# By the way we use dtype to find the datatype of the element
print(a.dtype)
print(b.dtype)

int64
int16


In [18]:
# To Transpose an array we can use the T attribute
print(a.T) # transpose of the array a
print()
print(b.T) # transpose of the array b

[1 2 3 4 5]

[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]


## Changing the Datatype

In [19]:
# We can change the data type of the array using the astype method
a_float = a.astype(float) # where we need to provide the new data type as an argument to the astype method
print(a_float)
print(a_float.dtype)

[1. 2. 3. 4. 5.]
float64


## Array Operations

In [20]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [21]:
print(a1)
print()
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### Scalar Operations

#### Arithmetic

In [33]:
a1 + 12 # element-wise addition

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [34]:
a1 - 2 # element-wise subtraction

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [35]:
a1*2 # element-wise multiplication with a scalar

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

``and every other arithmetic operation can be performed element-wise on numpy arrays, such as division, modulus, exponentiation, etc.``

#### Relative

In [41]:
# We can also use relational operators to compare two arrays element-wise
a1 < 10 # element-wise comparison, returns a boolean array

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False]])

In [39]:
a1 <= 12 # element-wise comparison, returns a boolean array

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [38]:
a1 == 11 # element-wise comparison, returns a boolean array

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

### Vector Operations

In [42]:
# Similar to scalar operations, we can also perform element-wise operations between two arrays of the same shape
a1 + a2 # element-wise addition

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [43]:
a1 - a2 # element-wise subtraction

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [44]:
a1 ^ a2 # element-wise bitwise XOR operation

array([[12, 12, 12, 12],
       [20, 20, 20, 20],
       [28, 28, 28, 28]])

`and similarly to the scalar operations we can perform all the arithmetic and relational operations using another vector.`

In [51]:
# Let's test with different shapes
a3 = np.arange(6).reshape(2, 3)
print(a3)
print()
a4 = np.arange(6, 12).reshape(3, 2)
print(a4)
print()
try :
    print(a3 + a4) # this will give an error because the shapes are not compatible for element-wise addition
    print()
except ValueError as e:
    print(e)
    print()
print(a3.dot(a4)) # but here we can perform matrix multiplication using the dot method because the inner dimensions are compatible (3 in a3 and 3 in a4)

[[0 1 2]
 [3 4 5]]

[[ 6  7]
 [ 8  9]
 [10 11]]

operands could not be broadcast together with shapes (2,3) (3,2) 

[[ 28  31]
 [100 112]]


### Descriptive Functions

In [66]:
np.max(a1) # find the maximum value in the array a1

11

In [67]:
np.min(a2) # minimum value in the array a2

12

In [68]:
np.prod(a2) # product of all elements in the array

647647525324800

In [69]:
np.sum(a1) # sum of all elements in the array

66

In [70]:
print(np.max(a1, axis=0)) # max along the columns
print(np.max(a1, axis=1)) # max along the rows

[ 8  9 10 11]
[ 3  7 11]


### Statistical Functions

In [73]:
# mean
print(np.mean(a1)) # mean of all elements in the array a1
print(np.median(a1)) # median of all elements in the array a1

# we can also use the mean and median functions along specific axes
print(np.mean(a1, axis=0)) # mean along the columns
print(np.mean(a1, axis=1)) # mean along the rows

# median
print(np.median(a1)) # median along the columns
print(np.median(a2)) # median along the rows

5.5
5.5
[4. 5. 6. 7.]
[1.5 5.5 9.5]
5.5
17.5


In [75]:
# std and var
print(np.std(a1)) # standard deviation of all elements in the array a1
print(np.var(a1)) # variance of all elements in the array a1

# we can also use the std and var functions along specific axes

3.452052529534663
11.916666666666666


### Trignometric Functions

In [76]:
# cos sin tan functions
print(np.cos(a1)) # cosine of all elements in the array a1
print(np.sin(a1)) # sine of all elements in the array a1
print(np.tan(a1)) # tangent of all elements in the array a1

[[ 1.          0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029  0.75390225]
 [-0.14550003 -0.91113026 -0.83907153  0.0044257 ]]
[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]
[[ 0.00000000e+00  1.55740772e+00 -2.18503986e+00 -1.42546543e-01]
 [ 1.15782128e+00 -3.38051501e+00 -2.91006191e-01  8.71447983e-01]
 [-6.79971146e+00 -4.52315659e-01  6.48360827e-01 -2.25950846e+02]]


In [79]:
# other trigonometric functions
a1_normalized = a1 / np.max(a1)  # normalize to [0, 1] range
print(np.arccos(a1_normalized))  # inverse cosine of normalized values
print(np.arcsin(a1_normalized))  # inverse sine of normalized values
print(np.arctan(a1))  # inverse tangent works with any value

[[1.57079633 1.47976155 1.38796119 1.2945697 ]
 [1.19862779 1.09893449 0.99386498 0.88102133]
 [0.75645638 0.61255474 0.42969967 0.        ]]
[[0.         0.09103478 0.18283514 0.27622663]
 [0.37216853 0.47186184 0.57693135 0.689775  ]
 [0.81433994 0.95824159 1.14109666 1.57079633]]
[[0.         0.78539816 1.10714872 1.24904577]
 [1.32581766 1.37340077 1.40564765 1.42889927]
 [1.44644133 1.46013911 1.47112767 1.48013644]]


### Dot product and Cross Product

In [90]:
# element-wise multiplication of two arrays
a1 = np.arange(1, 7).reshape(3, 2)
a2 = np.arange(5, 11).reshape(3, 2)
a1 * a2 # element-wise multiplication of two arrays of the same shape

array([[ 5, 12],
       [21, 32],
       [45, 60]])

In [91]:
# dot product of two arrays
a1 = np.arange(1, 7).reshape(3, 2)
a2 = np.arange(5, 11).reshape(2, 3)
a1.dot(a2) # dot product of two arrays of compatible shapes

array([[21, 24, 27],
       [47, 54, 61],
       [73, 84, 95]])

### Other Functions

In [ ]:
# find the determinant of a square matrix

a_square = np.array([[1, 2], [3, 4]])
print(np.linalg.det(a_square)) # determinant of the square matrix a_square

# Note to self : To explore the linalg module of numpy for more linear algebra operations like eigenvalues, singular value decomposition, etc.

-2.0000000000000004


In [92]:
# Log of an array
print(np.log(a1)) # natural logarithm of all elements in the array a1

[[0.         0.69314718]
 [1.09861229 1.38629436]
 [1.60943791 1.79175947]]


In [93]:
# exponential of an array
print(np.exp(a1)) # exponential of all elements in the array a1

[[  2.71828183   7.3890561 ]
 [ 20.08553692  54.59815003]
 [148.4131591  403.42879349]]


In [97]:
# round floor and ceil functions
a1 = np.linspace(0, 10, 20) # create an array of 5 values between 0 and 10
print(np.round(a1)) # round all elements in the array a1 to the nearest integer
print(np.floor(a1)) # floor of all elements in the array a1 (round down to the nearest integer)
print(np.ceil(a1)) # ceil of all elements in the array a1 (round up to the nearest integer)

[ 0.  1.  1.  2.  2.  3.  3.  4.  4.  5.  5.  6.  6.  7.  7.  8.  8.  9.
  9. 10.]
[ 0.  0.  1.  1.  2.  2.  3.  3.  4.  4.  5.  5.  6.  6.  7.  7.  8.  8.
  9. 10.]
[ 0.  1.  2.  2.  3.  3.  4.  4.  5.  5.  6.  6.  7.  7.  8.  8.  9.  9.
 10. 10.]


## Index Slicing

In [98]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

In [99]:
print(a1)
print()
print(a2)
print()
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


`To perform the indexing and slicing operations on the arrays, we can use the standard Python indexing and slicing syntax.
`

In [106]:
# Indexing 

print(a1[0]) # first element of the array a1
print(a2[1][0]) # first element of the first row of the array a2

# We can use another way to access the elements of the array using a single set of square brackets and comma-separated indices
print(a2[0, 3]) # first element of the first row of the array
print(a3[0, 1, 0]) # first element of the first block, first row and first column of the array a3

0
4
3
2


In [111]:
# slicing operations

print(a1[0:2]) # first two elements of the array a1
print()
print(a2[0:2, 1:3]) # first two rows and columns 1 and 2 of the array a2
print()
print(a3[0:1, 0:2, 0:2]) # first block, first two rows and first two columns of the array a3
print()

# We can also use negative indexing or steps in slicing
print(a1[-2:]) # last two elements of the array a1
print()
print(a2[::2, ::2]) # every other row and every other column of

[0 1]

[[1 2]
 [5 6]]

[[[0 1]
  [2 3]]]

[8 9]

[[ 0  2]
 [ 8 10]]


## Iterating

In [114]:
a1 = np.linspace(0, 10, 5) # create an array of 5 values between 0 and 10

for i in a1:
    print(i)

0.0
2.5
5.0
7.5
10.0


In [116]:
a2 = np.arange(12).reshape(3, 4)

for row in a2:
    print(row)
    for element in row:
        print(element)

[0 1 2 3]
0
1
2
3
[4 5 6 7]
4
5
6
7
[ 8  9 10 11]
8
9
10
11


In [118]:
# use an iterator to access the data
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


## Reshaping

In [119]:
# there are functions that reshape the array without changing the data, these are called view functions
a1 = np.arange(12).reshape(3, 4)
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [120]:
a1.reshape(2, 6) # reshape to 2 rows and 6 columns, this will return a new array with the new shape but the same data

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
a1.T # transpose of the array a1, this will return a new array with the transposed shape but the same data

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [122]:
a1.ravel() # flatten the array a1, this will return a new array with the same data but flattened to 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Stacking

In [123]:
# We can stack arrays vertically or horizontally using the vstack and hstack functions
a2 = np.arange(12).reshape(3, 4)
print(a2)
print()

a3 = np.arange(12).reshape(3, 4)
print(a3)
print()

a4 = np.vstack((a2, a3)) # stack a2 and a3 vertically
print(a4)
print()

a5 = np.hstack((a2, a3)) # stack a2 and a3 horizontally
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]]


In [124]:
# Now what if we try to stack arrays of different shapes, we will get an error because the shapes are not compatible for stacking
a6 = np.arange(6).reshape(2, 3)
print(a6)
print()
try:
    a7 = np.vstack((a2, a6)) # this will give an error because the shapes are not compatible for vertical stacking
    print(a7)
except ValueError as e:
    print(e)
    print()

[[0 1 2]
 [3 4 5]]

all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3



## Splitting

In [129]:
# Now we will use the splitting functions to split arrays into smaller arrays
a8 = np.arange(12).reshape(3, 4)
print(a8)
print()
a9 = np.hsplit(a8, 2) # split the array a8 into
print(a9) # this will split the array a8 into 2 equal parts horizontally
print()
a10 = np.vsplit(a8, 3) # split the array a8 into 3 equal parts vertically
print(a10) # this will split the array a8 into 3 equal parts vertically

a10[1].dtype # thus a10 is a list of 3 arrays, each of shape (1, 4) and dtype int64

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


dtype('int64')