# Daily Data Science 002i

This notebook is to cover some less frequently used numpy functions that are still used in Data Science.

In [28]:
# Importing the NumPy library
import numpy as np

# Numpy Extras

## Sorting

In [29]:
# To sort something we can use the built in sorted function.
# It takes an iterable and returns a new sorted list.

a = np.random.randint(1, 100, 10)
print(a)
print()
print(np.sort(a))
print(type(np.sort(a)))
print()

# We can also use the axis parameter to sort along a specific axis.
b = np.random.randint(1, 100, (3, 3))
print(b)
print()
print(np.sort(b, axis=0))  # Sort along the columns
print()
print(np.sort(b, axis=1))  # Sort along the rows

[69 89 59 37 40  2 84 31 20 63]

[ 2 20 31 37 40 59 63 69 84 89]
<class 'numpy.ndarray'>

[[82 87 22]
 [71 86 63]
 [38 48 60]]

[[38 48 22]
 [71 86 60]
 [82 87 63]]

[[22 82 87]
 [63 71 86]
 [38 48 60]]


## Appending

In [30]:
# To append we can use the np.append function. It takes an array, 
# values to append, and an optional axis parameter.
c = np.array([1, 2, 3])
print(c)
print()
print(np.append(c, 4)) # Append a single value

[1 2 3]

[1 2 3 4]


In [31]:
# To append in a 2d array we need to specify the axis.
b = np.append(b, [[10, 20, 30]], axis=0) # Append a new row
print(b)
print()

b = np.append(b, np.ones((b.shape[0], 1)), axis=1) # Append a new column
print(b)

[[82 87 22]
 [71 86 63]
 [38 48 60]
 [10 20 30]]

[[82. 87. 22.  1.]
 [71. 86. 63.  1.]
 [38. 48. 60.  1.]
 [10. 20. 30.  1.]]


## Concatenation

In [34]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [35]:
# to concat we can use the np.concatenate function. It takes a sequence of arrays and an optional axis parameter.

np.concatenate((c, d), axis=0) # Concatenate along the rows

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [36]:
np.concatenate((c, d), axis=1) # Concatenate along the columns

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## Unique

In [37]:
# to find the unique values in an array we can use the np.unique function. It takes an array and returns the sorted unique values.
a = np.array([1, 2, 3, 4, 5, 5, 6, 6, 7])
print(a)
print()
print(np.unique(a))

[1 2 3 4 5 5 6 6 7]

[1 2 3 4 5 6 7]


## Expand Dimensions

In [38]:
# To expand the dimensions of an array we can use the np.expand_dims function. It takes an array and an axis parameter and returns a new array with the dimensions expanded.
a = np.array([1, 2, 3])
print(a)
print()
print(np.expand_dims(a, axis=0)) # Expand along the rows
print()
print(np.expand_dims(a, axis=1)) # Expand along the columns

[1 2 3]

[[1 2 3]]

[[1]
 [2]
 [3]]


## Where

In [51]:
a = np.arange(10)
print(a)
print()
# We can use where to find the indices of the elements that satisfy a condition. It takes a condition and returns the indices of the elements that satisfy the condition.
print(np.where(a%2 == 0)) # Find the indices of the even numbers
print()
print(a[np.where(a%2 == 0)])

[0 1 2 3 4 5 6 7 8 9]

(array([0, 2, 4, 6, 8]),)

[0 2 4 6 8]


In [52]:
# We can also use where to get custom responses for the elements that satisfy a condition. It takes a condition, a value to return for the elements that satisfy the condition, and a value to return for the elements that do not satisfy the condition.
# np.where(condition, true, false) 
print(np.where(a%2 == 0, 'Even', 'Odd')) # Return 'Even' for even numbers and 'Odd' for odd numbers

['Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd']
