# Daily Data Science 002i

This notebook is to cover some less frequently used numpy functions that are still used in Data Science.

In [1]:
# Importing the NumPy library
import numpy as np

# Numpy Extras

## Sorting

In [2]:
# To sort something we can use the built in sorted function.
# It takes an iterable and returns a new sorted list.

a = np.random.randint(1, 100, 10)
print(a)
print()
print(np.sort(a))
print(type(np.sort(a)))
print()

# We can also use the axis parameter to sort along a specific axis.
b = np.random.randint(1, 100, (3, 3))
print(b)
print()
print(np.sort(b, axis=0))  # Sort along the columns
print()
print(np.sort(b, axis=1))  # Sort along the rows

[23 65 25  2  8 90 99 97 90 68]

[ 2  8 23 25 65 68 90 90 97 99]
<class 'numpy.ndarray'>

[[28 40 65]
 [95 68  7]
 [60 90 51]]

[[28 40  7]
 [60 68 51]
 [95 90 65]]

[[28 40 65]
 [ 7 68 95]
 [51 60 90]]


## Appending

In [3]:
# To append we can use the np.append function. It takes an array, 
# values to append, and an optional axis parameter.
c = np.array([1, 2, 3])
print(c)
print()
print(np.append(c, 4)) # Append a single value

[1 2 3]

[1 2 3 4]


In [4]:
# To append in a 2d array we need to specify the axis.
b = np.append(b, [[10, 20, 30]], axis=0) # Append a new row
print(b)
print()

b = np.append(b, np.ones((b.shape[0], 1)), axis=1) # Append a new column
print(b)

[[28 40 65]
 [95 68  7]
 [60 90 51]
 [10 20 30]]

[[28. 40. 65.  1.]
 [95. 68.  7.  1.]
 [60. 90. 51.  1.]
 [10. 20. 30.  1.]]


## Concatenation

In [5]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print()
print(d)

[[0 1 2]
 [3 4 5]]

[[ 6  7  8]
 [ 9 10 11]]


In [6]:
# to concat we can use the np.concatenate function. It takes a sequence of arrays and an optional axis parameter.

np.concatenate((c, d), axis=0) # Concatenate along the rows

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
np.concatenate((c, d), axis=1) # Concatenate along the columns

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## Unique

In [8]:
# to find the unique values in an array we can use the np.unique function. It takes an array and returns the sorted unique values.
a = np.array([1, 2, 3, 4, 5, 5, 6, 6, 7])
print(a)
print()
print(np.unique(a))

[1 2 3 4 5 5 6 6 7]

[1 2 3 4 5 6 7]


## Expand Dimensions

In [9]:
# To expand the dimensions of an array we can use the np.expand_dims function. It takes an array and an axis parameter and returns a new array with the dimensions expanded.
a = np.array([1, 2, 3])
print(a)
print()
print(np.expand_dims(a, axis=0)) # Expand along the rows
print()
print(np.expand_dims(a, axis=1)) # Expand along the columns

[1 2 3]

[[1 2 3]]

[[1]
 [2]
 [3]]


## Where

In [10]:
a = np.arange(10)
print(a)
print()
# We can use where to find the indices of the elements that satisfy a condition. It takes a condition and returns the indices of the elements that satisfy the condition.
print(np.where(a%2 == 0)) # Find the indices of the even numbers
print()
print(a[np.where(a%2 == 0)])

[0 1 2 3 4 5 6 7 8 9]

(array([0, 2, 4, 6, 8]),)

[0 2 4 6 8]


In [11]:
# We can also use where to get custom responses for the elements that satisfy a condition. It takes a condition, a value to return for the elements that satisfy the condition, and a value to return for the elements that do not satisfy the condition.
# np.where(condition, true, false) 
print(np.where(a%2 == 0, 'Even', 'Odd')) # Return 'Even' for even numbers and 'Odd' for odd numbers

['Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd']


## ArgMax

In [12]:
# np.argmax is used to find the indices of the maximum values along an axis.
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a, "\n")
print(np.argmax(a, axis=0)) # Find the indices of the maximum values along the columns
print(np.argmax(a, axis=1)) # Find the indices of the maximum values along the rows
print(np.argmax(a)) # Find the index of the maximum value in the flattened array

[[1 2 3]
 [4 5 6]] 

[1 1 1]
[2 2]
5


In [13]:
# Similarly, np.argmin is used to find the indices of the minimum values along an axis.
print(np.argmin(a, axis=0)) # Find the indices of the minimum values along
print(np.argmin(a, axis=1)) # Find the indices of the minimum values along the rows
print(np.argmin(a)) # Find the index of the minimum value in the flattened array

[0 0 0]
[0 0]
0


## Cumulative Sum

In [14]:
# np.cumsum is used to find the cumulative sum of the elements along an axis.
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a, "\n")
print(np.cumsum(a, axis=0)) # Find the cumulative sum along the columns

[[1 2 3]
 [4 5 6]] 

[[1 2 3]
 [5 7 9]]


In [15]:
# for a simple 1d array
a = np.array([1, 2, 3, 4, 5])
print(a, "\n")
print(np.cumsum(a)) # Find the cumulative sum of the elements in the array

[1 2 3 4 5] 

[ 1  3  6 10 15]


In [16]:
# Similarly we have np.cumprod to find the cumulative product of the elements along an axis.
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a, "\n")
print(np.cumprod(a, axis=0), "\n") # Find the cumulative product along the columns
print(np.cumprod(a, axis=1)) # Find the cumulative product along the rows

[[1 2 3]
 [4 5 6]] 

[[ 1  2  3]
 [ 4 10 18]] 

[[  1   2   6]
 [  4  20 120]]


## Percentile

np.percentile() is used to compute the nth percentile of the given data alongside the given axes.

In [17]:
# np.percentile is used to find the percentile of the elements along an axis. It takes an array, a percentile value, and an optional axis parameter.
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a, "\n")
print(np.percentile(a, 0)) # Find the 0th percentile (minimum)
print(np.percentile(a, 50)) # Find the 50th percentile (median)
print(np.percentile(a, 25)) # Find the 25th percentile (first quartile)
print(np.percentile(a, 75)) # Find the 75th percentile (third quartile)
print(np.percentile(a, 100)) # Find the 100th percentile (maximum)

[[1 2 3]
 [4 5 6]] 

1.0
3.5
2.25
4.75
6.0


## Histogram

np.histogram() represents the frequency of data distribution in graphical form.

In [18]:
# np.histogram is used to compute the histogram of the elements in an array. It takes an array and a number of bins and returns the histogram and the bin edges.
a = np.random.randint(1, 100, 100)
hist, bin_edges = np.histogram(a, bins=10)
print("Histogram:", hist)
print("Bin edges:", bin_edges)

Histogram: [13 11  8 13  6  6 14 11  8 10]
Bin edges: [ 1.  10.8 20.6 30.4 40.2 50.  59.8 69.6 79.4 89.2 99. ]


In [19]:
# we can also specify the bins
a = np.random.randint(1, 100, 100)
bins = [0, 20, 40, 60, 80, 100]
hist, bin_edges = np.histogram(a, bins=bins)
print("Histogram:", hist)
print("Bin edges:", bin_edges)

Histogram: [14 22 21 20 23]
Bin edges: [  0  20  40  60  80 100]


## Correlation Coefficient

np.corrcoef() returns the Pearson product moment correlation coefficients.

In [20]:
# np.corrcoef is used to find the correlation coefficient between two arrays. It takes two arrays and returns the correlation coefficient.
salary = np.array([50000, 60000, 55000, 80000, 75000])
experience = np.array([1, 2, 3, 4, 5])
correlation_coefficient = np.corrcoef(salary, experience)
print(correlation_coefficient)
print("Correlation coefficient between salary and experience:", correlation_coefficient[0, 1])

[[1.         0.85518611]
 [0.85518611 1.        ]]
Correlation coefficient between salary and experience: 0.8551861104941365


## Is In

numpy.isin() is used to check if the elements of an array are present in another array. It takes two arrays and returns a boolean array / mask indicating whether each element of the first array is present in the second array.

In [21]:
# numpy.isin() is used to check if the elements of an array are present in another array. It takes two arrays and returns a boolean array indicating whether each element of the first array is present in the second array.
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])
print(np.isin(a, b)) # Check if the elements of a are present in b
print(np.isin(b, a)) # Check if the elements of b are present in a

[False False  True  True  True]
[ True  True  True False False]


## Flip

In [22]:
# np.flip() is used to reverse the order of the elements in an array along a specified axis. It takes an array and an optional axis parameter and returns a new array with the elements flipped.
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print()
print(np.flip(a, axis=0)) # Flip along the rows
print()
print(np.flip(a, axis=1)) # Flip along the columns

[[1 2 3]
 [4 5 6]]

[[4 5 6]
 [1 2 3]]

[[3 2 1]
 [6 5 4]]


## Put

In [24]:
# numpy.put() is used to set the values of an array at specific indices. It takes an array, indices, and values to set at those indices.
a = np.array([1, 2, 3, 4, 5])
print(a)
print()
np.put(a, [0, 2], [10, 30]) # Set the values at indices 0 and 2 to 10 and 30 respectively. Also edits inplace.
print(a)

[1 2 3 4 5]

[10  2 30  4  5]


## Delete

In [28]:
# numpy.delete() is used to delete elements from an array at specific indices. It takes an array and indices to delete and returns a new array with the elements deleted.
a = np.array([1, 2, 3, 4, 5])
print(a)
print(id(a))
print()
a = np.delete(a, [0, 2]) # Delete the elements at indices 0 and 2. Also returns a new array.
print(a)
print(id(a))
print()

# It can also be used to delete elements along a specific axis in a 2d array.
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print()
b = np.delete(b, 0, axis=0) # Delete the first row
print(b)
print()
b = np.delete(b, 1, axis=1) # Delete the second column
print(b)

[1 2 3 4 5]
134984617804112

[2 4 5]
134984617804208

[[1 2 3]
 [4 5 6]]

[[4 5 6]]

[[4 6]]


## Set Functions

In [31]:
# Set functions are present in numpy.
# np.union1d() is used to find the union of two arrays. It takes two arrays and returns a new array containing the unique values that are present in either of the input arrays.
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
print(a)
print(b)
print()
print("Union - ",np.union1d(a, b)) # Find the union of a and b
print("Intersection - ",np.intersect1d(a, b)) # Find the intersection of a and b
print("Set Difference - ",np.setdiff1d(a, b)) # Find the set difference of a and b
print("Symmetric Difference - ",np.setxor1d(a, b)) # Find the symmetric difference of a and b
print("Numpy np.in1d() - ", np.in1d(a, b)) # Check if elements of a are in b

[1 2 3 4 5]
[4 5 6 7 8]

Union -  [1 2 3 4 5 6 7 8]
Intersection -  [4 5]
Set Difference -  [1 2 3]
Symmetric Difference -  [1 2 3 6 7 8]
Numpy np.in1d() -  [False False False  True  True]


## Clip

In [32]:
## np.clip() is used to limit the values in an array. It takes an array, a minimum value, and a maximum value and returns a new array with the values limited to the specified range.
a = np.array([1, 2, 3, 4, 5])
print(a)
print()
print(np.clip(a, 2, 4)) # Limit the values in a to the
# range [2, 4]. Values less than 2 will be set to 2 and values greater than 4 will be set to 4.

[1 2 3 4 5]

[2 2 3 4 4]
