<a href="https://colab.research.google.com/github/ProtoSol/Daily-Data-Science/blob/main/Daily_Data_Science_Day_42_43.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Revision of the Numpy Library

The Link to the Numpy -> [Numpy](https://numpy.org/)

`What is Numpy?`

NumPy (Numerical Python) is a library for the Python programming language that adds support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. It is designed to provide efficient numerical computation and is widely used in scientific computing and data analysis

In [1]:
# Installing numpy library
# !pip install numpy

# Import the Library
import numpy as np

## Basic Commands of Numpy

Simple Array

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


Zeros filled Array, Ones filled array

In [3]:
arr = np.zeros(2)
arr2 = np.ones(2)
print(arr)
print(arr2)

[0. 0.]
[1. 1.]


Empty Array

In [5]:
np.empty(2)

array([1., 1.])

Creating array for a range of number n

In [6]:
np.arange(4)

array([0, 1, 2, 3])

Making two dimensional Array

In [7]:
a = np.array([1, 2, 3])
print(a)
a2 = a[np.newaxis, :]
print(a2)

[1 2 3]
[[1 2 3]]


Finding the shape of the Array

In [9]:
print(a.shape)
print(a2.shape)

(3,)
(1, 3)


Make an array and fill the array with one value.

In [10]:
a = np.full((2, 2), 7)
print(a)

[[7 7]
 [7 7]]


Make Identity Matrix

In [11]:
identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


We can check the datatype of the array

In [14]:
a = np.array([1, 2, 3])
print(a.dtype) # Type of Data in the Array
print(type(a)) # Type of the Data

int64
<class 'numpy.ndarray'>


To get the Dimension of the Array

In [15]:
a.ndim

1

To find the size of the Array

In [16]:
a.size

3

---


In data science, one-dimensional (1D), two-dimensional (2D), and three-dimensional (3D) arrays are used to represent and manipulate various types of data. Each type of array serves a specific purpose depending on the nature of the data and the operations needed to be performed on it.\
`1D Arrays`\
1D arrays are used to represent a single sequence of values, such as:
- A list of numbers
- A series of dates
- A sequence of characters
They are commonly used in data science for tasks like:
- Data preprocessing
- Feature engineering
- Statistical analysis
- Machine learning model inputs\
`2D Arrays`\
2D arrays, also known as matrices, are used to represent tables or grids of data. They are commonly used in data science for tasks like:
- Data visualization
- Data manipulation
- Matrix operations
- Linear algebra
- Machine learning model inputs\
`3D Arrays`\
3D arrays are used to represent three-dimensional data structures, such as:
- 3D images
- 3D models
- 3D data in scientific simulations
- 3D data in machine learning models
They are commonly used in data science for tasks like:
- Image processing
- Computer vision
- Scientific simulations
- Machine learning model inputs


In summary, the choice of array dimension depends on the nature of the data and the operations needed to be performed on it.

## Basic Operations

Subtraction of elements

In [18]:
g = a - 2
print(g)

[-1  0  1]


Addition of Two Arrays

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print(c)

[5 7 9]


In [20]:
# Another way
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.add(a, b)
print(c)

[5 7 9]


Multiplication of Arrays

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
print(c)

[ 4 10 18]


Division of Arrays

In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a / b
print(c)

[0.25 0.4  0.5 ]
