<a href="https://colab.research.google.com/github/ProtoSol/Daily-Data-Science/blob/main/Daily_Data_Science_Day_42_45.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Revision of the Numpy Library

The Link to the Numpy -> [Numpy](https://numpy.org/)

`What is Numpy?`

NumPy (Numerical Python) is a library for the Python programming language that adds support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays. It is designed to provide efficient numerical computation and is widely used in scientific computing and data analysis

In [ ]:
# Installing numpy library
# !pip install numpy

# Import the Library
import numpy as np

## Basic Commands of Numpy

Simple Array

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


Zeros filled Array, Ones filled array

In [ ]:
arr = np.zeros(2)
arr2 = np.ones(2)
print(arr)
print(arr2)

[0. 0.]
[1. 1.]


Empty Array

In [ ]:
np.empty(2)

array([1., 1.])

Creating array for a range of number n

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

Making two dimensional Array

In [ ]:
a = np.array([1, 2, 3])
print(a)
a2 = a[np.newaxis, :]
print(a2)

[1 2 3]
[[1 2 3]]


Finding the shape of the Array

In [ ]:
print(a.shape)
print(a2.shape)

(3,)
(1, 3)


Make an array and fill the array with one value.

In [ ]:
a = np.full((2, 2), 7)
print(a)

[[7 7]
 [7 7]]


Make Identity Matrix

In [ ]:
identity = np.eye(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


We can check the datatype of the array

In [ ]:
a = np.array([1, 2, 3])
print(a.dtype) # Type of Data in the Array
print(type(a)) # Type of the Data

int64
<class 'numpy.ndarray'>


To get the Dimension of the Array

In [ ]:
a.ndim

1

To find the size of the Array

In [ ]:
a.size

3

---


In data science, one-dimensional (1D), two-dimensional (2D), and three-dimensional (3D) arrays are used to represent and manipulate various types of data. Each type of array serves a specific purpose depending on the nature of the data and the operations needed to be performed on it.\
`1D Arrays`\
1D arrays are used to represent a single sequence of values, such as:
- A list of numbers
- A series of dates
- A sequence of characters
They are commonly used in data science for tasks like:
- Data preprocessing
- Feature engineering
- Statistical analysis
- Machine learning model inputs\
`2D Arrays`\
2D arrays, also known as matrices, are used to represent tables or grids of data. They are commonly used in data science for tasks like:
- Data visualization
- Data manipulation
- Matrix operations
- Linear algebra
- Machine learning model inputs\
`3D Arrays`\
3D arrays are used to represent three-dimensional data structures, such as:
- 3D images
- 3D models
- 3D data in scientific simulations
- 3D data in machine learning models
They are commonly used in data science for tasks like:
- Image processing
- Computer vision
- Scientific simulations
- Machine learning model inputs


In summary, the choice of array dimension depends on the nature of the data and the operations needed to be performed on it.

## Basic Operations

Subtraction of elements

In [ ]:
g = a - 2
print(g)

[-1  0  1]


Addition of Two Arrays

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print(c)

[5 7 9]


In [ ]:
# Another way
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.add(a, b)
print(c)

[5 7 9]


Multiplication of Arrays

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a * b
print(c)

[ 4 10 18]


Division of Arrays

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a / b
print(c)

[0.25 0.4  0.5 ]


------

# Numpy Revision 2

## Importing the Library

In [1]:
import numpy as np

## Codes

In [2]:
# Empty Array of Numpy
empty = np.empty((2, 2))
print(empty)

[[4.74034133e-310 0.00000000e+000]
 [3.30426893e-033 1.33440016e-317]]


In [3]:
# Numpy array using Arrange function
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# We can also Step in the Arrange function
arr = np.arange(10, 20, 2)
arr2 = np.arange(11, 20, 2)
print(arr)

[10 12 14 16 18]


Linearly Spaced Array

In [8]:
lin = np.linspace(1, 10, 5)
print(lin)

[ 1.    3.25  5.5   7.75 10.  ]


We can also define the datatype for the numpy array.

In [11]:
lin = np.linspace(1, 10, 5, dtype=float)
print(lin)
print(lin.dtype)

[ 1.    3.25  5.5   7.75 10.  ]
float64


In [13]:
# We can also sort the array
arr = np.array([5,4,2,3,1])
print(np.sort(arr))

[1 2 3 4 5]


Concatination of the array

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b))
print(c)

[1 2 3 4 5 6]


In [15]:
# We can also make it inplace
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a = np.concatenate((a, b))
print(a)

[1 2 3 4 5 6]


## 2D Arrays

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [20]:
# Concatination of the 2d Arrays
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.concatenate((a, b))
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
# Concatinate using Different axis
c = np.concatenate((a, b), axis=1)
print(c)

# Now for axis = 0
c = np.concatenate((a, b), axis=0)
print(c)
print(c.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


## 3D Array

In [24]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a)
print('------')
print(a.shape)
print('------')
print(a.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
------
(2, 2, 3)
------
3


In [25]:
# Reshaping an Array
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b)

[[1 2 3]
 [4 5 6]]


## Indexing and Slicing

In [28]:
# Indexing property of Numpy array
a = np.array([1, 2, 3, 4, 5, 6])
print(a[2])

# Slicing property of Numpy array
print(a[1:4])
print(a[1:])
# Stepping Property
print(a[::-1])

3
[2 3 4]
[2 3 4 5 6]
[6 5 4 3 2 1]


In [29]:
# Indexing property in 2d Array
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[0, 1])

# Slicing property in 2d Array
print(a[0:2, 1:])

2
[[2 3]
 [5 6]]


## Filtering Property

In [30]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a[a > 3])

[4 5 6]


In [33]:
a = np.arange(21)
print(a[a % 2 == 0])
print(a[a % 2 != 0])

[ 0  2  4  6  8 10 12 14 16 18 20]
[ 1  3  5  7  9 11 13 15 17 19]


In [34]:
# Using multiple conditions
a = np.array([1, 2, 3, 4, 5, 6])
print(a[(a > 2) & (a < 5)])

[3 4]


In [35]:
# Conditions using other Condition types
a = np.array([1, 2, 3, 4, 5, 6])
print(a[np.logical_and(a > 2, a < 5)])

[3 4]


## Creating Arrays from Data

In [36]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b)

[[1 2 3]
 [4 5 6]]


In [37]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3, order='F')
print(b)

[[1 3 5]
 [2 4 6]]


In [38]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[a < 4]
print(b)

[1 2 3]


##Hstack and Vstack Function

In [39]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.vstack((a, b))
print(c)

[[1 2 3]
 [4 5 6]]


In [40]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.hstack((a, b))
print(c)

[1 2 3 4 5 6]


## Creating Matrices

In [41]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [44]:
b = np.matrix([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.dtype)

[[1 2 3]
 [4 5 6]]
int64


In [65]:
a = np.arange(0,1000,5).reshape(10, 20)
print(a)

[[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
   90  95]
 [100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180 185
  190 195]
 [200 205 210 215 220 225 230 235 240 245 250 255 260 265 270 275 280 285
  290 295]
 [300 305 310 315 320 325 330 335 340 345 350 355 360 365 370 375 380 385
  390 395]
 [400 405 410 415 420 425 430 435 440 445 450 455 460 465 470 475 480 485
  490 495]
 [500 505 510 515 520 525 530 535 540 545 550 555 560 565 570 575 580 585
  590 595]
 [600 605 610 615 620 625 630 635 640 645 650 655 660 665 670 675 680 685
  690 695]
 [700 705 710 715 720 725 730 735 740 745 750 755 760 765 770 775 780 785
  790 795]
 [800 805 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885
  890 895]
 [900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
  990 995]]


## Aggregate Functions

In [66]:
a.sum()

99500

In [67]:
a.max()

995

In [68]:
a.mean()

497.5

In [69]:
a.std()

288.6715261330774

In [70]:
a.var()

83331.25

In [71]:
a.min()

0

In [72]:
a.argmin()

0

In [73]:
a.max(axis=1)

array([ 95, 195, 295, 395, 495, 595, 695, 795, 895, 995])

In [75]:
np.array([[1,2,3],[4,5,6]]) + np.array([[1,2,3],[4,5,6]])

array([[ 2,  4,  6],
       [ 8, 10, 12]])